<?php
require_once 'config.php';

// Check connection
if (!$conn) {
    $e = oci_error();
    die("Connection Error: " . $e['message']);
}

echo "Connected to Oracle successfully!<br><br>";

// SQL to create users table
$sql = "BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE users';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -942 THEN
                RAISE;
            END IF;
    END;
    
    EXECUTE IMMEDIATE 'CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(50) UNIQUE NOT NULL,
        email VARCHAR2(100) UNIQUE NOT NULL,
        password VARCHAR2(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )';
END;";

$stid = oci_parse($conn, $sql);

if (!$stid) {
    $e = oci_error($conn);
    die("Parse Error: " . $e['message']);
}

$r = oci_execute($stid);

if ($r) {
    echo "Database table 'users' created successfully!";
} else {
    $e = oci_error($stid);
    echo "Error creating table: " . $e['message'];
    echo "<br>SQL Text: " . $e['sqltext'];
}

oci_free_statement($stid);

// Add unique constraint to HMS2.EMP_HMS2_TABLE for CPF_NO
echo "<br><br>Adding unique constraint to HMS2.EMP_HMS2_TABLE.CPF_NO...<br>";

$alter_sql = "BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE HMS2.EMP_HMS2_TABLE ADD CONSTRAINT uk_emp_cpf UNIQUE (CPF_NO)';
        DBMS_OUTPUT.PUT_LINE('Unique constraint added successfully.');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -2261 THEN
                DBMS_OUTPUT.PUT_LINE('Constraint already exists.');
            ELSIF SQLCODE = -942 THEN
                DBMS_OUTPUT.PUT_LINE('HMS2.EMP_HMS2_TABLE does not exist.');
            ELSE
                RAISE;
            END IF;
    END;
END;";

$alter_stid = oci_parse($conn, $alter_sql);

if (!$alter_stid) {
    $e = oci_error($conn);
    echo "Parse Error: " . $e['message'];
} else {
    $r = oci_execute($alter_stid);
    if ($r) {
        echo "Unique constraint on CPF_NO added successfully (or already exists)!";
    } else {
        $e = oci_error($alter_stid);
        echo "Error adding constraint: " . $e['message'];
    }
    oci_free_statement($alter_stid);
}

oci_close($conn);
?>
